"use client";

import React, { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";
import SanctumModal from "@/components/SanctumModal";
import InterpretationDisplay from "@/components/InterpretationDisplay";
import { generateInterpretation } from "@/app/user/interpret/actions";
import { loginHrefFor } from "@/lib/auth-return-path";
import type { CardVisuals } from "@/components/SpreadCards";
import type { Interpretation } from "@/types/interpret";

// Generate persists server-side in the same call and is idempotent (one
// interpretation per reading, ever) — so there is no unsaved state, no save
// step, and no close-without-saving concern.
type ModalState = "confirm" | "generating" | "result" | "error";

const SHORT_MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

// Format a "YYYY-MM-DD" birthdate as "12 Mar 1990" (matches readings list style)
const formatBirthDate = (iso: string): string => {
  const [year, month, day] = iso.split("-").map(Number);
  return `${day} ${SHORT_MONTHS[month - 1]} ${year}`;
};

const CINZEL = { fontFamily: "'Cinzel', serif" } as const;
const GOLD_BUTTON = "bg-gradient-to-br from-[#d4af37] to-[#b8942f] text-[#1a0033] rounded-lg font-bold";

interface InterpretationModalProps {
  readingId: string;
  spreadName: string;
  question?: string;
  birthDate?: string;
  cardVisuals: CardVisuals;
  onClose: () => void;
  // Fired when the modal closes after an interpretation was generated (it is
  // already persisted) so the parent can refresh or navigate to the journal
  onComplete: () => void;
  autoGenerate?: boolean;
}

const InterpretationModal: React.FC<InterpretationModalProps> = React.memo(({
  readingId,
  spreadName,
  question,
  birthDate,
  cardVisuals,
  onClose,
  onComplete,
  autoGenerate = false,
}) => {
  const [modalState, setModalState] = useState<ModalState>(
    autoGenerate ? "generating" : "confirm"
  );
  const [interpretation, setInterpretation] = useState<Interpretation | null>(null);
  const [remainingBudget, setRemainingBudget] = useState<number | null>(null);
  const [errorMessage, setErrorMessage] = useState("");
  // Set when a request came back unauthenticated: retrying cannot succeed, so
  // the UI offers a plain login round-trip back to the reading page instead
  const [sessionExpired, setSessionExpired] = useState(false);

  const isFetchingRef = useRef(false);

  // The interpretation (if any) is already persisted, so closing is always
  // safe — but the parent still needs to know one now exists
  const handleClose = useCallback(() => {
    if (interpretation) onComplete();
    onClose();
  }, [interpretation, onComplete, onClose]);

  const runGenerate = useCallback(async () => {
    if (isFetchingRef.current) return;
    isFetchingRef.current = true;
    setModalState("generating");
    try {
      const result = await generateInterpretation(readingId);
      if (result.ok) {
        // A 200 with a blank narrative is a degenerate LLM response — surface
        // it as a failure rather than rendering an empty reading
        if (!result.data.reading.trim()) {
          setErrorMessage("The oracle returned no interpretation. Please try again.");
          setModalState("error");
          return;
        }
        setInterpretation(result.data);
        setRemainingBudget(result.remainingBudgetUsd);
        setModalState("result");
      } else {
        setErrorMessage(result.error);
        if (result.unauthenticated) setSessionExpired(true);
        setModalState("error");
      }
    } catch {
      setErrorMessage("The oracle could not be reached.");
      setModalState("error");
    } finally {
      isFetchingRef.current = false;
    }
  }, [readingId]);

  // When opened with autoGenerate, start generating immediately — once
  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (!autoGenerate || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    runGenerate();
  }, [autoGenerate, runGenerate]);

  // After login the user lands back on the reading page and generates again
  const loginHref = loginHrefFor(`/user/readings/${readingId}`);

  // Once the session is gone the primary action becomes "log in"; otherwise
  // it is the ordinary button
  const primaryAction = (
    label: React.ReactNode,
    loginLabel: string,
    onClick: () => void,
    className: string
  ) =>
    sessionExpired ? (
      <Link href={loginHref} className={className} style={CINZEL}>
        {loginLabel}
      </Link>
    ) : (
      <button onClick={onClick} className={className} style={CINZEL}>
        {label}
      </button>
    );

  const subtitle = birthDate ? `${spreadName} · ${formatBirthDate(birthDate)}` : spreadName;

  return (
    <SanctumModal title="Interpretation" subtitle={subtitle} size="lg" onClose={handleClose}>
      {/* GENERATING STATE */}
      {modalState === "generating" && (
        <div className="flex flex-col items-center gap-6 py-16">
          <div className="w-16 h-16 border-4 border-[#d4af37]/20 border-t-[#d4af37] rounded-full animate-spin" />
          <p
            className="text-[#d4af37]/80 text-lg tracking-wider"
            style={{ fontFamily: "'Cinzel', serif" }}
          >
            The Oracle consults the stars...
          </p>
        </div>
      )}

      {/* ERROR STATE (generate failed) */}
      {modalState === "error" && (
        <div className="flex flex-col items-center gap-6 py-8">
          <p
            className="text-red-400 text-center text-base"
            style={{ fontFamily: "'Crimson Pro', serif" }}
          >
            {errorMessage || "The oracle could not be reached."}
          </p>
          {primaryAction(
            "Try Again",
            "Log In",
            runGenerate,
            "px-8 py-3 border border-[#d4af37]/40 text-[#d4af37] hover:bg-[#d4af37]/10 rounded-lg transition-all text-sm"
          )}
        </div>
      )}

      {/* RESULT STATE — the interpretation is already saved */}
      {modalState === "result" && interpretation && (
        <div className="flex flex-col gap-8">
          <InterpretationDisplay
            question={question}
            narrative={interpretation.reading}
            cardVisuals={cardVisuals}
          />

          <div className="flex flex-col items-center gap-3">
            <button
              onClick={handleClose}
              className={`px-10 py-3 ${GOLD_BUTTON} shadow-lg hover:shadow-[#d4af37]/50 transition-all text-sm tracking-[0.1em]`}
              style={CINZEL}
            >
              ✦ Done ✦
            </button>
            {remainingBudget !== null && (
              <p
                className="text-xs text-[#e6d5b8]/40"
                style={{ fontFamily: "'Crimson Pro', serif" }}
              >
                Saved to your journal · Remaining Oracle budget ${remainingBudget.toFixed(2)}
              </p>
            )}
          </div>
        </div>
      )}

      {/* CONFIRM STATE */}
      {modalState === "confirm" && (
        <div className="flex flex-col gap-8">
          <p
            className="text-center text-sm text-[#e6d5b8]/60"
            style={{ fontFamily: "'Crimson Pro', serif" }}
          >
            Ready to consult the Oracle for this reading?
          </p>

          <div className="flex justify-center">
            <button
              onClick={runGenerate}
              className="px-10 py-3 bg-gradient-to-br from-[#8a2be2]/80 to-[#5a1a9e]/80 text-[#e6d5b8] rounded-lg
                         font-bold shadow-lg hover:shadow-[#8a2be2]/40 transition-all text-sm border border-[#8a2be2]/40"
              style={{ fontFamily: "'Cinzel', serif", letterSpacing: "0.1em" }}
            >
              ✦ Consult the Oracle ✦
            </button>
          </div>
        </div>
      )}
    </SanctumModal>
  );
});

InterpretationModal.displayName = "InterpretationModal";

export default InterpretationModal;
