"""Regenerate the generated regions of docs/prompt_reference.md from the real prompt code.

The doc has two marker-delimited regions:

    <!-- BEGIN GENERATED: blocks (make prompt-doc) --> ... <!-- END GENERATED: blocks -->
    <!-- BEGIN GENERATED: sample (make prompt-doc) --> ... <!-- END GENERATED: sample -->

Everything outside the markers is hand-written and preserved.

Usage:
    python -m scripts.dump_prompts          # rewrite the doc in place
    python -m scripts.dump_prompts --check  # exit 1 if the doc is stale, write nothing
"""

import argparse
import sys
from pathlib import Path

from src.llm import prompt_components
from src.llm.prompt_builder import (
    REASONING_HEADROOM,
    build_system_prompt,
    build_user_prompt,
    max_completion_tokens,
    request_word_budget,
)
from src.llm.schemas import (
    CardInSpread,
    InterpretationLens,
    InterpretationRequest,
    InterpretationSettings,
    LLMInterpretationResult,
    Orientation,
    ReadingIntent,
)

DOC_PATH = Path(__file__).resolve().parent.parent / "docs" / "prompt_reference.md"

SAMPLE_REQUEST = InterpretationRequest(
    spread_name="Past-Present-Future",
    question="Should I take the job offer in Lisbon?",
    cards=[
        CardInSpread(name="The Lovers", position="Past", orientation=Orientation.upright),
        CardInSpread(
            name="Five of Disks",
            position="Present",
            orientation=Orientation.reversed,
            position_description="What is active now",
        ),
        CardInSpread(name="Queen of Cups", position="Future", orientation=Orientation.upright),
    ],
    settings=InterpretationSettings(
        lens=InterpretationLens.esoteric, intent=ReadingIntent.reflective, depth=60
    ),
)


def _begin(name: str) -> str:
    return f"<!-- BEGIN GENERATED: {name} (make prompt-doc) -->"


def _end(name: str) -> str:
    return f"<!-- END GENERATED: {name} -->"


def replace_between_markers(text: str, name: str, body: str) -> str:
    """Replace the region between the `name` markers with `body`, keeping the markers."""
    begin, end = _begin(name), _end(name)
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1 or stop < start:
        raise ValueError(f"marker pair for '{name}' not found in document")
    return text[: start + len(begin)] + "\n" + body.strip("\n") + "\n" + text[stop:]


def _fence(text: str) -> str:
    return "```text\n" + text.strip("\n") + "\n```"


def render_blocks() -> str:
    out: list[str] = [
        "_Generated from `src/llm/prompt_components.py` and `src/llm/schemas.py` — "
        "edit the source, then run `make prompt-doc`._",
        "",
    ]
    for label, text in prompt_components.named_blocks():
        out += [f"#### {label}", "", _fence(text), ""]

    schema = LLMInterpretationResult.model_json_schema()
    card_props = schema["$defs"]["CardInterpretation"]["properties"]
    descriptions = [
        ("card_interpretations", schema["properties"]["card_interpretations"]["description"]),
        ("card_interpretations[].interpretation", card_props["interpretation"]["description"]),
        ("synthesis", schema["properties"]["synthesis"]["description"]),
    ]
    out += [
        "#### Response-format field descriptions (`LLMInterpretationResult`)",
        "",
        "Sent to OpenAI as `response_format`; the model reads these alongside the system prompt.",
        "",
    ]
    for field, description in descriptions:
        out += [f"- `{field}` — {description}"]
    return "\n".join(out)


def render_sample() -> str:
    request = SAMPLE_REQUEST
    words_per_card, synthesis_words = request_word_budget(request)
    cards = len(request.cards)
    caps = ", ".join(
        f"{effort}: {max_completion_tokens((words_per_card, synthesis_words), cards, effort)}"
        for effort in REASONING_HEADROOM
    )
    card_lines = [
        f"- {c.name} ({c.orientation.value}) — {c.position}"
        + (f" — {c.position_description}" if c.position_description else "")
        for c in request.cards
    ]
    out = [
        "_Generated by `scripts/dump_prompts.py` from a fixed sample request — "
        "one major, one pip, one court._",
        "",
        f"- Spread: {request.spread_name}",
        f"- Question: {request.question}",
        f"- Settings: lens={request.settings.lens.value}, "
        f"intent={request.settings.intent.value}, depth={request.settings.depth}",
        *card_lines,
        f"- Word budget: {words_per_card} words per card, {synthesis_words} for the synthesis",
        f"- `max_completion_tokens` by reasoning effort: {caps}",
        "",
        "#### System prompt",
        "",
        _fence(build_system_prompt(request)),
        "",
        "#### User prompt",
        "",
        _fence(build_user_prompt(request)),
    ]
    return "\n".join(out)


def render_doc(text: str) -> str:
    text = replace_between_markers(text, "blocks", render_blocks())
    return replace_between_markers(text, "sample", render_sample())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if the doc is stale; write nothing"
    )
    args = parser.parse_args(argv)

    current = DOC_PATH.read_text(encoding="utf-8")
    rendered = render_doc(current)
    if args.check:
        if rendered == current:
            print(f"{DOC_PATH.name}: up to date")
            return 0
        print(f"{DOC_PATH.name}: stale — run `make prompt-doc`")
        return 1
    DOC_PATH.write_text(rendered, encoding="utf-8")
    print(f"{DOC_PATH.name}: regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
